# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  2distributedcacheredis:
    image: 2distributedcacheredis
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5147:5147
    networks:
      - my_network
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis-cache
    ports:
      - 6378:6379
    restart: always
    networks:
      - my_network

networks:
  my_network:
